# create_user.py

import argparse
from pathlib import Path
from client import *
from constants import *

secrets_path = Path(".streamlit") / "secrets.toml"

template = """[[users]]
key="{}"

"""

client = BotpressClient()


def create_user(name, id, add_to_secrets=True):
    res = client.create_user(name, id)
    if not add_to_secrets:
        return res

    secrets_path.touch(exist_ok=True)

    with open(secrets_path, "a") as f:
        f.write(template.format(res["user"]["id"], res["key"]))

    return res


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Create a Botpress user and optionally store secrets."
    )
    parser.add_argument("--name", required=True, help="Display name of the user.")
    parser.add_argument(
        "--id", required=True, help="User ID. If omitted, one is generated by the API."
    )
    parser.add_argument("--chat_api_id", help="ID for the Botpress Chat API integration. Taken from `.env` file if not provided.")
    parser.add_argument(
        "--no-secrets",
        action="store_true",
        help="Do not append to .streamlit/secrets.toml.",
    )

    args = parser.parse_args()

    print(f"Creating user: {args.name} (ID: {args.id or 'auto-generated'})")
    result = create_user(name=args.name, id=args.id, add_to_secrets=not args.no_secrets)

    print("✅ User created:")
    print(result)
